---
automation:
  - alias: Button Office
    id: da3e3cb9-4f13-4d65-9d4c-f684888c2398
    mode: queued
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "00:15:8d:00:01:d8:db:30"
    action:
      choose:
        # Single Click
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.args.click_type == 'single' }}"
          sequence:
            - service: light.toggle
              data:
                entity_id: light.fado_desk
                brightness: 150
                kelvin: 4000
        # Double Click
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.args.click_type == 'double' }}"
          sequence:
            - service: light.toggle
              data:
                entity_id:
                  - light.fado_desk
                  - light.office_desk
                brightness: 150
                kelvin: 4000

  - alias: Button Living
    id: 6b4f2245-d39a-4190-a846-c51dffcaae4e
    mode: queued
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "00:15:8d:00:01:87:0a:c2"
    action:
      choose:
        # Single Click
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.args.click_type == 'single' }}"
          sequence:
            - service: light.toggle
              entity_id: light.living_floor_light
        # Double Click
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.args.click_type == 'double' }}"
          sequence:
            - service: script.toggle_ambilight_hue

  - alias: Button Bedroom
    id: 72c9f90d-7208-46ee-88d7-c1055f51f61a
    mode: queued
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: "00:15:8d:00:01:bc:f8:00"
    action:
      choose:
        # Single Click
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.args.click_type == 'single' }}"
          sequence:
            - service: light.toggle
              data:
                entity_id: light.go
                brightness: 75
                color_name: orange
        # Double Click
        - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.args.click_type == 'double' }}"
          sequence:
            - service: media_player.media_stop
              entity_id: media_player.bed_chromecast
