---
automation:
  - alias: Light Hall
    id: c2df6567-a636-48a3-8c86-fec73b866634
    description: Turn on the light in the hall when presence is detected or turn it off if there is no motion.
    mode: restart
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: state
        entity_id:
          - binary_sensor.presence_hall
          - input_boolean.motion_sensor
          - alarm_control_panel.ha_alarm
          - sensor.illuminance_hall
    action:
      choose:
        # Motion detected
        - conditions:
            - condition: state
              entity_id: binary_sensor.presence_hall
              state: 'on'
            - condition: numeric_state
              entity_id: sensor.illuminance_hall
              below: 75
            - condition: state
              entity_id: alarm_control_panel.ha_alarm
              state: disarmed
            - condition: state
              entity_id: input_boolean.motion_sensor
              state: 'on'
          sequence:
            - service: switch.turn_on
              entity_id: switch.circadian_lighting_hall
            - service: light.turn_on
              data:
                entity_id: light.flur
                transition: 2
              data_template:
                kelvin: >-
                  {{ state_attr('sensor.circadian_values', 'colortemp') | int }}
                brightness_pct: >-
                  {{ state_attr('switch.circadian_lighting_hall', 'brightness') | int }}
      # No more motion detected
      default:
        - service: switch.turn_off
          entity_id: switch.circadian_lighting_hall
        - service: light.turn_off
          data:
            entity_id: light.flur
            transition: 3

  - alias: Light Kitchen
    id: 0c2d7924-c4c3-4fd6-83de-b1f0d8a9c893
    description: Turn on the light in the kitchen in the evening when presence is detected or turn it off if there is no motion.
    mode: restart
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: state
        entity_id:
          - binary_sensor.presence_kitchen
          - input_boolean.motion_sensor
          - alarm_control_panel.ha_alarm
    action:
      choose:
        # Motion detected
        - conditions:
            - condition: state
              entity_id: binary_sensor.presence_kitchen
              state: 'on'
            - condition: state
              entity_id: alarm_control_panel.ha_alarm
              state: disarmed
            - condition: state
              entity_id: input_boolean.motion_sensor
              state: 'on'
            - condition: time
              before: "07:00:00"
              after: "21:00:00"
          sequence:
            - service: switch.turn_on
              entity_id: switch.circadian_lighting_kitchen
            - service: light.turn_on
              data:
                entity_id: light.kitchen_cabinets
                transition: 2
              data_template:
                kelvin: >-
                  {{ state_attr('sensor.circadian_values', 'colortemp') | int }}
                brightness_pct: >-
                  {{ state_attr('switch.circadian_lighting_kitchen', 'brightness') | int }}
      # No more motion detected
      default:
        - service: switch.turn_off
          entity_id: switch.circadian_lighting_kitchen
        - service: light.turn_off
          data:
            entity_id: light.kitchen_cabinets
            transition: 3
  
  - alias: Light Storage
    id: 00ddb44e-5948-4502-bc1b-749ca649b4a8
    description: Turn off the light in the storage after a few minutes
    mode: restart
    trigger:
      - platform: homeassistant
        event: start
      - platform: event
        event_type: automation_reloaded
      - platform: state
        entity_id:
          - light.storage
    condition:
      - condition: state
        entity_id: light.storage
        state: 'on'
    action:
      - delay: '00:02:30'
      - service: light.turn_off
        entity_id: light.storage
