# lovelace_gen
{% set home_feed_entities = [
'alarm_control_panel.ha_alarm',
'binary_sensor.presence_kitchen',
'binary_sensor.presence_hall',
'binary_sensor.contact_office',
'binary_sensor.contact_kitchen',
'binary_sensor.contact_bed',
'binary_sensor.contact_bath',
'binary_sensor.contact_door',
'binary_sensor.contact_living_door',
'binary_sensor.contact_living_window',
] %}
- title: Einstellungen
  icon: mdi:cog
  path: settings
  cards:
    - type: vertical-stack
      cards:
        - !include 
          - ../includes/header.yaml
          - title: Wecker

        - type: vertical-stack
          cards:
            - !include 
              - ../includes/section.yaml
              - title: Funktionen
            - type: custom:time-picker-card
              entity: input_datetime.alarm_time
            - !include
              - ../includes/grid.yaml
              - entities: 
                  - entity_id: input_boolean.alarm_clock
                    name: Wecker
                  - entity_id: input_boolean.motion_sensor
                    name: Bewegungsmelder
                  - entity_id: input_boolean.vacation_mode
                    name: Urlaub

        - type: vertical-stack
          cards:
            - !include 
              - ../includes/section.yaml
              - title: Home Feed
            - type: logbook
              title: " "
              entities:
                {% for entity in home_feed_entities %}
                - {{ entity }}
                {% endfor %}

        - type: custom:grocy-chores-card
          entity: sensor.grocy_chores
          title: Aufgaben