---
esphome:
  name: light_office_closet
  platform: ESP8266
  board: d1_mini_lite
  includes:
    - diyhueasyncudp.h
  libraries:
    - ESPAsyncUDP@697c75a025

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

api:
  password: !secret esp_apipass

logger:

ota:
  password: !secret esp_otapass

light:
  - platform: fastled_clockless
    name: "color_led"
    id: color_led
    chipset: WS2812B
    pin: D4
    num_leds: 200
    rgb_order: GRB

web_server:
  port: 80

custom_component:
- lambda: |-
    auto diyhue = new diyhueudp();
    return {diyhue};

text_sensor:
  - platform: template
    name: "light_id"
    id: light_id
    lambda: |-
      return {"esphome_diyhue_light;bc:dd:c2:7a:d7:d6;Closet;0;0"};
    update_interval: 24h

switch:
  - platform: template
    name: alert
    id: alert
    optimistic: true
    turn_on_action:
      - light.turn_off: color_led
      - light.turn_on:
          id: color_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: color_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: color_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: color_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_off: color_led
      - switch.turn_off: alert
  - platform: template
    name: entertainment_switch
    id: entertainment_switch
    optimistic: true
