---
substitutions:
  name: Schreibtisch
  device: light_office_desk
  pin: GPIO3
  num_leds: '139'
  mac: '50:02:91:79:49:0d'

packages:
  diyhue_base: !include common/diyhue_base.yaml
  main_base: !include common/main_base.yaml
