---
esphome:
  name: light_living_couch
  platform: ESP8266
  board: d1_mini_lite
  includes:
    - diyhueasyncudp.h
  libraries:
    - ESPAsyncUDP@697c75a025

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

api:
  password: !secret esp_apipass

logger:
  level: DEBUG

ota:
  password: !secret esp_otapass

status_led:
  pin:
    number: D2
    inverted: True

remote_transmitter:
  pin: D6
  carrier_duty_percent: 50%

remote_receiver:
  pin:
    number: D5
    inverted: true
  dump: all

light:
  - platform: fastled_clockless
    name: "color_led"
    id: color_led
    chipset: WS2812B
    # RX
    pin: GPIO3
    num_leds: 108
    rgb_order: GRB

web_server:
  port: 80

custom_component:
- lambda: |-
    auto diyhue = new diyhueudp();
    return {diyhue};

text_sensor:
  - platform: template
    name: "light_id"
    id: light_id
    lambda: |-
      return {"esphome_diyhue_light;50:02:91:78:d5:a0;Couch;0;0"};
    update_interval: 24h

switch:
  - platform: template
    name: alert
    id: alert
    optimistic: true
    turn_on_action:
      - light.turn_off: color_led
      - light.turn_on:
          id: color_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: color_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: color_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: color_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_off: color_led
      - switch.turn_off: alert
  - platform: template
    name: entertainment_switch
    id: entertainment_switch
    optimistic: true
    
  - platform: template
    name: "Soundbar Power Button"
    turn_on_action:
      remote_transmitter.transmit_raw:
        carrier_frequency: 38kHz
        code: [4502, -4500, 495, -509, 494, -509, 494, -510, 493, -509, 494, -1512, 494, -1512, 494, -510, 493, -510, 494, -1511, 494, -1513, 494, -1512, 495, -1511, 494, -510, 494, -509, 494, -512, 492, -510, 493, -4523, 494, -510, 494, -510, 493, -509, 496, -508, 494, -510, 494, -509, 494, -510, 495, -508, 494, -1515, 492, -1512, 495, -1512, 494, -510, 494, -1512, 494, -1513, 495, -1511, 494, -1515, 492, -510, 494, -509, 494, -510, 493, -1517, 490]
  - platform: template
    name: "Soundbar Source Button"
    turn_on_action:
      remote_transmitter.transmit_raw:
        code: [4502, -4498, 496, -507, 496, -507, 496, -507, 496, -507, 496, -1510, 496, -1509, 497, -507, 496, -507, 496, -1510, 496, -1509, 497, -1509, 497, -1510, 496, -507, 496, -508, 498, -504, 496, -508, 495, -4519, 496, -507, 496, -508, 495, -508, 495, -508, 495, -1511, 496, -507, 496, -1510, 496, -507, 496, -1509, 497, -1509, 498, -1507, 497, -507, 496, -509, 494, -1510, 496, -507, 496, -1509, 497, -507, 496, -507, 496, -507, 496, -1509, 496]
  - platform: template
    name: "Soundbar Volume Up Button"
    turn_on_action:
      remote_transmitter.transmit_raw:
        code: [-4497, 497, -507, 496, -507, 496, -507, 496, -507, 496, -1510, 496, -1509, 496, -508, 496, -507, 496, -1509, 497, -1509, 496, -1510, 496, -1509, 496, -507, 496, -508, 498, -504, 496, -507, 496, -4518, 496, -508, 495, -508, 495, -508,  495, -508, 495, -508, 496, -507, 495, -508, 495, -1510, 496, -1510, 496, -1510, 496, -1510, 496, -507, 496, -1510, 495, -1510, 496, -1510, 496, -508, 497, -505, 495, -508, 495, -508, 497, -1508, 496]
  - platform: template
    name: "Soundbar Volume Down Button"
    turn_on_action:
      remote_transmitter.transmit_raw:
        code: [4502, -4499, 497, -506, 497, -506, 497, -506, 497, -506, 497, -1509, 496, -1509, 497, -506, 497, -506, 497, -1508, 498, -1507, 497, -1509, 497, -1509, 498, -505, 497, -506, 496, -507, 496, -507, 496, -4517, 499, -504, 497, -507, 496, -506, 496, -507, 496, -507, 496, -507, 496, -507, 496, -1509, 497, -1511, 494, -1508, 497, -1509, 497, -506, 497, -1509, 499, -1505, 498, -1508, 497, -506, 497, -506, 496, -507, 496, -507, 496, -1509, 497]
